# Generated by Django 6.0.4 on 2026-05-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(null=True)),
                ('tipo', models.CharField(choices=[('prata', 'Prata'), ('ouro', 'Ouro'), ('diamante', 'Diamante')])),
            ],
        ),
    ]
