# Generated by Django 6.0.5 on 2026-05-14 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_tipouser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apoiador',
            options={'verbose_name_plural': 'Apoiadores'},
        ),
        migrations.AlterModelOptions(
            name='tipoedicao',
            options={'verbose_name_plural': 'Tipo de Edições'},
        ),
        migrations.AlterField(
            model_name='apoiador',
            name='nome',
            field=models.CharField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='apoiador',
            name='tipo',
            field=models.CharField(choices=[('prata', 'Prata'), ('ouro', 'Ouro'), ('diamante', 'Diamante')], default=('prata', 'Prata')),
        ),
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('inscricao', 'Inscrição'), ('emAndamento', 'Em andamento'), ('avaliacao', 'Avaliação'), ('finalizado', 'Finalizado')], default='inscricao', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('minimo_participantes', models.PositiveIntegerField()),
                ('maximo_participantes', models.PositiveIntegerField()),
                ('maximo_equipes', models.PositiveIntegerField()),
                ('apoiadores', models.ManyToManyField(blank=True, related_name='Edições', to='hackathon.apoiador')),
                ('tipo_edicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Edições', to='hackathon.tipoedicao')),
            ],
            options={
                'verbose_name_plural': 'Edições',
            },
        ),
    ]
