# Generated by Django 6.0.4 on 2026-05-14 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_alter_apoiador_options_alter_tipoedicao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicao',
            name='apoiadores',
            field=models.ManyToManyField(blank=True, related_name='edicoes', to='hackathon.apoiador'),
        ),
        migrations.AlterField(
            model_name='edicao',
            name='status',
            field=models.CharField(choices=[('INSCRICAO', 'Inscrição'), ('EM_ANDAMENTO', 'Em andamento'), ('AVALIACAO', 'Avaliação'), ('FINALIZADO', 'Finalizado')], default='INSCRICAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='edicao',
            name='tipo_edicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edicoes', to='hackathon.tipoedicao'),
        ),
    ]
