# Generated by Django 6.0.4 on 2026-05-23 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_alter_edicao_apoiadores_alter_edicao_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_tema', models.CharField(max_length=45)),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temas', to='hackathon.edicao')),
            ],
            options={
                'verbose_name_plural': 'Temas',
            },
        ),
    ]
