# Generated by Django 6.0.4 on 2026-05-16 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_alter_edicao_apoiadores_alter_edicao_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criterios', to='hackathon.edicao')),
            ],
        ),
    ]
