# Generated by Django 6.0.4 on 2026-05-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_criterio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterio',
            options={'verbose_name_plural': 'Critérios'},
        ),
    ]
