# Generated by Django 6.0.5 on 2026-05-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_tema'),
        ('hackathon', '0006_alter_criterio_options'),
    ]

    operations = [
    ]
