# Generated by Django 6.0.4 on 2026-05-29 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_merge_0005_tema_0006_alter_criterio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoiador',
            name='nome',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='apoiador',
            name='tipo',
            field=models.CharField(choices=[('prata', 'Prata'), ('ouro', 'Ouro'), ('diamante', 'Diamante')], default=('prata', 'Prata'), max_length=20),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=100)),
                ('descricao_projeto', models.TextField()),
                ('link_deploy_projeto', models.URLField(blank=True, null=True)),
                ('notaFinal_projeto', models.IntegerField(blank=True, null=True)),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='hackathon.edicao')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='hackathon.tema')),
            ],
            options={
                'verbose_name_plural': 'Projetos',
            },
        ),
    ]
