# Generated by Django 6.0.6 on 2026-06-12 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_alter_apoiador_nome_alter_apoiador_tipo_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(max_length=50)),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='hackathon.edicao')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='hackathon.projeto')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='hackathon.tema')),
            ],
            options={
                'verbose_name_plural': 'Equipes',
                'unique_together': {('nome_equipe', 'edicao')},
            },
        ),
    ]
