# Generated by Django 6.0.4 on 2026-06-13 19:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_alter_apoiador_nome_alter_apoiador_tipo_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comentario_nota', models.TextField(blank=True, null=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='hackathon.criterio')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='hackathon.projeto')),
            ],
        ),
    ]
