# Generated by Django 6.0.4 on 2026-08-31 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0012_populate_tipo_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hackathon_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
