# Generated by Django 6.0.6 on 2026-08-31 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0013_alter_user_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='projeto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='hackathon.projeto'),
        ),
    ]
