# Generated by Django 6.0.6 on 2026-09-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0014_alter_equipe_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipoUser',
            field=models.CharField(choices=[('PARTICIPANTE', 'Participante'), ('AVALIADOR', 'Avaliador'), ('ADMIN', 'Administrador')], default='PARTICIPANTE', max_length=20),
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='tema',
        ),
        migrations.CreateModel(
            name='ParticipanteEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participantes', to='hackathon.equipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='hackathon.user')),
            ],
            options={
                'verbose_name_plural': 'Participantes Equipe',
                'unique_together': {('user', 'equipe')},
            },
        ),
        migrations.DeleteModel(
            name='TipoUser',
        ),
    ]
