# Generated by Django 6.0.6
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0018_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliadorEdicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliadores', to='hackathon.edicao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edicoes_avaliador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliador da Edição',
                'verbose_name_plural': 'Avaliadores da Edição',
                'unique_together': {('user', 'edicao')},
            },
        ),
    ]
