# Generated by Django 6.0.6
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0019_avaliadoredicao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterField(
            model_name='projeto',
            name='notaFinal_projeto',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name='nota',
            name='avaliador',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='notas',
                to='hackathon.avaliadoredicao',
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('projeto', 'criterio', 'avaliador')},
        ),
    ]
