# Generated by Django 6.0.6 on 2026-09-29 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0020_alter_nota_options_nota_avaliador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='hackathon.criterio'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='hackathon.projeto'),
        ),
    ]
